export const products = [
  {
    id: 1,
    title: "Girasol",
    price: 1000,
    stock: 500,
    description: "Semillas de girasol",
    category: "flores",
    img: "https://coderhouse-react.s3.amazonaws.com/fotos/girasol.jpg",
  },
  {
    id: 2,
    title: "Coliflor",
    price: 1500,
    stock: 100,
    description: "Semillas de coliflor",
    category: "verduras",
    img: "https://coderhouse-react.s3.amazonaws.com/fotos/coliflor.jpg",
  },
  {
    id: 3,
    title: "Lavanda",
    price: 750,
    stock: 100,
    description: "Semillas de lavanda",
    category: "flores",
    img: "https://coderhouse-react.s3.amazonaws.com/fotos/lavanda.jpg",
  },
  {
    id: 4,
    title: "Mandarina",
    price: 3000,
    stock: 50,
    description: "Semillas de mandarina",
    category: "frutas",
    img: "https://coderhouse-react.s3.amazonaws.com/fotos/mandarina.jpg",
  },
  {
    id: 5,
    title: "Rosa blanca",
    price: 5000,
    stock: 5,
    description: "Semillas de rosa",
    category: "flores",
    img: "https://coderhouse-react.s3.amazonaws.com/fotos/rosa.jpg",
  },
  {
    id: 6,
    title: "Tomate",
    price: 100,
    stock: 500,
    description: "Semillas de tomate",
    category: "frutas",
    img: "https://coderhouse-react.s3.amazonaws.com/fotos/tomate.jpg",
  },
  {
    id: 7,
    title: "Zanahoria",
    price: 200,
    stock: 250,
    description: "Semillas de zanahoria",
    category: "verduras",
    img: "https://coderhouse-react.s3.amazonaws.com/fotos/zanahoria.jpg",
  },
  {
    id: 8,
    title: "Zapallo",
    price: 500,
    stock: 100,
    description: "Semillas de zapallo",
    category: "verduras",
    img: "https://coderhouse-react.s3.amazonaws.com/fotos/zapallo.jpg",
  },
];
